---
repos:
  - repo: 'https://github.com/gruntwork-io/pre-commit'
    rev: v0.1.23
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: shellcheck
  - repo: local
    hooks:
      - id: biome-lint
        name: biome lint
        entry: pnpm biome lint
        pass_filenames: false
        language: node
      - id: biome-format
        name: biome format
        entry: pnpm biome format
        pass_filenames: false
        language: node
      - id: ajv
        name: ajv
        entry: lib/scripts/ajv.ts
        pass_filenames: false
        language: node
      - id: yamllint
        name: yamllint
        entry: yamllint .
        pass_filenames: false
        language: system
